capstone/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static

from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', accounts_views.dashboard, name='dashboard'),
    path('tickets/', include('tickets.urls')),
    path('helpdesk/', include('helpdesk.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.urls import path

from tickets import views

urlpatterns = [
    path('create_ticket/', views.create_ticket, name='create_ticket'),
    path('<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('update_ticket/<int:ticket_id>/', views.update_ticket, name='update_ticket'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from PIL import Image

class User(AbstractUser):
    pass

    def __str__(self):
        return self.username
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone = models.CharField(max_length=100, blank=True)
    image = models.ImageField(default='default.jpg',upload_to='profile_pics')
    title = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
            super().save()
            img = Image.open(self.image.path)
    
class Department(models.Model):
    name = models.CharField(max_length=128)
    employees = models.ManyToManyField(User, default=None, blank=True, related_name='employees')

    def __str__(self):
        return self.name
    
    

tickets/models.py
from django.db import models
from django.utils import timezone

from accounts.models import User


class Ticket(models.Model):
    TYPE_OF_ISSUE = [
        ('HARDWARE', 'Hardware'),
        ('SOFTWARE', 'Software'),
        ('ACCOUNT', 'Account'),
        ('PASSWORD', 'Password'),
        ('OTHER', 'Other'),
    ]
    STATUS = [
        ('OPEN', 'Open'),
        ('ASSIGNED', 'Assigned'),
        ('UNDER_REVIEW', 'Under review'),
        ('AWAITING_RESPONSE', 'Awaiting response'),
        ('IN_PROCESS', 'In process'),
        ('COMPLETE', 'Complete')
    ]
    type_of_issue = models.CharField(
        max_length=10, choices=TYPE_OF_ISSUE, blank=True, default='HARDWARE')
    status = models.CharField(max_length=20, null=True,
                              choices=STATUS, default='OPEN')
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='customer')
    title = models.CharField(max_length=200)
    details = models.TextField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    assigned_tech = models.ForeignKey(User, on_delete=models.SET_NULL,
                                      blank=True, null=True, related_name='assigned_tech')
    due_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.id} - {self.title}"
    
    def total_by_type(self):
        return self.type_of_issue.count()
    
class TechNotes(models.Model):
    tech = models.ForeignKey(User, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='tech_notes')
    note = models.TextField(blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return 'Date: {} by {}'.format(self.created, self.tech)

tickets/forms.py
from django.forms import ModelForm, Textarea, TextInput, Select, DateInput, DateField

from tickets.models import Ticket, TechNotes
from accounts.models import User 
    

class CreateTicketForm(ModelForm):
    class Meta:
        model = Ticket 
        fields = ("title", "details", "type_of_issue")
        
        widgets = {
            'type_of_issue': Select(attrs={'class': 'form-control'}),
            'title': TextInput(attrs={'class': 'form-control'}),
            'details': Textarea(attrs={'class': 'form-control', 'cols': 40, 'rows': 3}),
        }
        
class UpdateTicketForm(ModelForm):    
    class Meta:
        model = Ticket
        fields = ("status", "due_date", "assigned_tech")
        
        widgets = {
            'status': Select(attrs={'class': 'form-control'}),
            'due_date': DateInput(
                attrs={
                'type': 'date',
                'class': 'form-control'
                }
            ),
            'assigned_tech': Select(attrs={'class': 'form-control'})
        }
        
    def __init__(self, *args, **kwargs):
        super(UpdateTicketForm, self).__init__(*args, **kwargs)
        self.fields['assigned_tech'].queryset = User.objects.filter(groups__name='IT Support').order_by('last_name')
        
        
class TechNotesForm(ModelForm):
    class Meta:
        model = TechNotes
        fields = ('note',)

        widgets = {
            'note': Textarea(attrs={'class': 'form-control', 'cols': 80, 'rows': 3})
        }

tickets/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from helpdesk.decorators import it_staff_required

from accounts.models import User
from tickets.models import Ticket, TechNotes
from tickets.forms import CreateTicketForm, UpdateTicketForm, TechNotesForm

@login_required
def create_ticket(request):
    form = CreateTicketForm()
    
    if request.method == 'POST':
        form = CreateTicketForm(request.POST)
    
    if form.is_valid():
        new_ticket = form.save(commit=False)
        new_ticket.customer = request.user
        new_ticket.status = "OPEN" 
        new_ticket.save()
        
        messages.success(request, f'Your ticket has been submitted.')
        return redirect('profile')
    else:
        form = CreateTicketForm()
    
    context = {
            'form': form,
            }
    return render(request, "tickets/create_ticket.html", context)

    
@login_required
def ticket_detail(request, ticket_id):
    ticket = Ticket.objects.get(pk=ticket_id)
    
    context = {
        'ticket': ticket,
    }
    return render(request, "partials/_ticket_detail.html", context)


@it_staff_required
def update_ticket(request, ticket_id):
    # techs = User.objects.filter(groups__name='IT Support').order_by('last_name').values()
    ticket = Ticket.objects.get(pk=ticket_id)
    
    if request.method == 'POST':
        update_form = UpdateTicketForm(request.POST, instance=ticket)
        notes_form = TechNotesForm(request.POST)
    
        if update_form.is_valid():
            update_form.save()
            
        if notes_form.is_valid:
            new_note = notes_form.save(commit=False)
            new_note.tech = request.user
            new_note.ticket = ticket
            new_note.save()

        messages.success(request, f'The ticket has been updated.')
        return redirect('it_dashboard')
    else:
        update_form = UpdateTicketForm(instance=ticket)
        notes_form = TechNotesForm()
        
    tech_notes = TechNotes.objects.filter(ticket=ticket).order_by('-created')
        
    context = {
        'ticket': ticket,
        'update_form': update_form,
        'notes_form': notes_form,
        'tech_notes': tech_notes
    }
   
    return render(request, "tickets/update_ticket.html", context)
    

templates/partials/_messages.html
<!-- Messages -->
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container pt-5 mt-5">
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_navbar.html
<!-- Navbar -->
{% load static %}

<nav class="navbar navbar-expand-lg bg-primary navbar-dark fixed-top shadow">
  <div class="container">
    <a class="navbar-brand" href="{% url 'dashboard' %}">
      <img src="{% static '/img/logo.png' %}" class="logo" alt="logo" width="30"/>  IT Help Desk 
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto mb-lg-0 d-flex align-items-center">
        {% if  perms.tickets %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'it_dashboard' %}">
            IT Staff Dashboard
          </a>
        </li>
         {% endif %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_ticket' %}">Submit a Ticket</a>
        </li>
            <li class="nav-item">
              <a class="nav-link align-self-baseline" href="{% url 'profile' %}">
                <img
                  class="rounded-circle"
                  width="40"
                  src="{{ user.profile.image.url }}"
                  alt="profile pic" />  Profile
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
        {% else %}
            <span class="navbar-text fw-bolder">
              <em>Logged in as: Guest</em>
            </span>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/partials/_profile-modal.html
<!-- Modal -->
{% load static %}
<div class="modal fade" id="profileModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5" id="myModalLabel">
					<img class="mb-4" src="{% static 'img/helpdesk.jpg' %}" alt="" width="50" />
					Update Profile
				</h1>
				<button class="btn-close" data-bs-dismiss="modal"></button>
			</div>
			<div class="modal-body">
				<form action="{% url 'update_profile'  %}" method="POST" enctype="multipart/form-data" id="post-form">
					{% csrf_token %}
					<div class="row">
						<div class="mb-4 col">
							<label for="title" class="form-label">Title</label>
							<input type="text" name="title" class="form-control" placeholder="Title"
								value="{{ user_profile.title }}" />
						</div>
						<div class="mb-4 col">
							<label for="phone" class="form-label">Phone Number</label>
							<input class="form-control" type="phone" name="phone" placeholder="Phone number"
								value="{{ user_profile.phone }}" />
						</div>
					</div>
					<div class="row">
						<div class="mb-4 col">
							<!-- cropper area-->
							<label for="id_image">Profile Picture</label>
							<input type="file" id="id_image" name="image" accept="image/*">
						</div>
					</div>
					<div class="row">
						<div class="mb-4 col">
							<!-- cropper image-box-->
							<div id="image-box" class="image-container"></div>
							<button class="btn btn-info text-white" id="crop-btn"
								style="width: 100%; margin-top: 10px; display: none;" type="button">Crop</button>
						</div>
					</div>
					<div class="modal-footer">
						<button class="btn btn-primary" type="submit" id="confirm-btn">
							Save changes
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

templates/partials/_ticket_detail.html
<!-- Modal -->
<div class="modal fade" id="ticketModal{{ ticket.id }}">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h1 class="modal-title fs-5" id="modalLabel">
            Ticket Number: <strong>{{ ticket.id }}</strong>
        </h1>
        <button class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
			<h6 class="card-subtitle my-3 text-muted">
				Created on:
				<span class="fw-bold">
					{{ ticket.created_date }}
				</span>
			</h6>
			<h6 class="card-subtitle my-2 text-muted">
				Opened by:
				<span class="fw-bold"
					>{{ ticket.customer.first_name }} 
					{{ ticket.customer.last_name }}
				</span>
			</h6>
			<p>
				<span class="text-muted">Subject:</span>
				<span class="fw-bold">{{ ticket.title }}</span>
			</p>
			<p>
				<span class="text-muted">Details:</span>
				<span>{{ ticket.details }}</span>
			</p>
			{% if ticket.assignedTech %}
			<p>
				<span class="text-muted">Assigned Tech: </span>
				{{ ticket.assignedTech.user.firstName }} 
				{{ ticket.assignedTech.user.lastName }}
			</p>
			{% endif %}
			<p class="text-muted">
				Status:
				<span class="text-danger fw-bold">
					{{ ticket.get_status_display }}
				</span>
			</p>
        </div>
        <div class="modal-footer">
        <button class="btn btn-secondary" data-bs-dismiss="modal">
            Close
        </button>
        </div>
    </div>
    </div>
</div>
<!-- End modal -->

templates/partials/_tickets.html
<!-- Tickets -->
{% if tickets %}
<div class="container">
	<div class="row">
		{% for ticket in tickets %}
		<div class="col-lg-6 mb-4">
			<div class="card shadow">
				<div class="card-header">
					<h5 class="card-title">
						Ticket Number: <strong> {{ ticket.id }} </strong>
					</h5>
				</div>
				<div class="card-body">
					<h6 class="card-subtitle my-2 text-muted">
						Opened by:
						<span class="fw-bold"
							>{{ ticket.customer.first_name }} 
							{{ ticket.customer.last_name }}</span
						>
					</h6>
					<p class="card-text">
						<span class="text-muted">Subject:</span>
						<span class="fw-bold">{{ ticket.title }}</span>
					</p>
					{% if ticket.assignedTech %}
					<p class="card-text">
						<span class="text-muted">Assigned Tech: </span>
						{{ ticket.assignedTech.user.firstName }} 
						{{ ticket.assignedTech.user.lastName }}
					</p>
					{% endif %}
					<p class="text-muted">
						Status:
						<span class="text-danger fw-bold">
							{{ ticket.get_status_display }}
						</span>
					</p>

					{% if ticket.customer == user %}
					<button  href="{% url 'ticket_detail' ticket.id %}" class="btn btn-primary btn-modal" data-bs-toggle="modal" data-bs-target="#ticketModal{{ ticket.id }}">
							Ticket Details
					</button>

					{% else %}
						<input type="hidden" name="next" value="{{ request.path }}">
						<a href="{% url 'update_ticket' ticket.id %}" class="btn btn-primary">
							Update Ticket
						</a>
					{% endif %}
				</div>
			</div>
		</div>
		{% include "partials/_ticket_detail.html" %}
		{% endfor %}
	</div>
</div>

{% endif %}