capstone/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static

from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', accounts_views.dashboard, name='dashboard'),
    path('tickets/', include('tickets.urls')),
    path('helpdesk/', include('helpdesk.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helpdesk/urls.py
from django.urls import path

from helpdesk import views

urlpatterns = [
    path('tech-chart/', views.tech_chart, name='tech_chart'),
    path('chart-data/', views.chart_data, name='chart_data'),
    path('', views.it_dashboard, name='it_dashboard'),
]

tickets/urls.py
from django.urls import path

from tickets import views

urlpatterns = [
    path('create_ticket/', views.create_ticket, name='create_ticket'),
    path('<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('update_ticket/<int:ticket_id>/', views.update_ticket, name='update_ticket'),
]

helpdesk/models.py
from django.db import models

# Create your models here.

tickets/models.py
from django.db import models
from django.utils import timezone

from accounts.models import User


class Ticket(models.Model):
    TYPE_OF_ISSUE = [
        ('HARDWARE', 'Hardware'),
        ('SOFTWARE', 'Software'),
        ('ACCOUNT', 'Account'),
        ('PASSWORD', 'Password'),
        ('OTHER', 'Other'),
    ]
    STATUS = [
        ('OPEN', 'Open'),
        ('ASSIGNED', 'Assigned'),
        ('UNDER_REVIEW', 'Under review'),
        ('AWAITING_RESPONSE', 'Awaiting response'),
        ('IN_PROCESS', 'In process'),
        ('COMPLETE', 'Complete')
    ]
    type_of_issue = models.CharField(
        max_length=10, choices=TYPE_OF_ISSUE, blank=True, default='HARDWARE')
    status = models.CharField(max_length=20, null=True,
                              choices=STATUS, default='OPEN')
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='customer')
    title = models.CharField(max_length=200)
    details = models.TextField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    assigned_tech = models.ForeignKey(User, on_delete=models.SET_NULL,
                                      blank=True, null=True, related_name='assigned_tech')
    due_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.id} - {self.title}"
    
    def total_by_type(self):
        return self.type_of_issue.count()
    
class TechNotes(models.Model):
    tech = models.ForeignKey(User, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='tech_notes')
    note = models.TextField(blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return 'Date: {} by {}'.format(self.created, self.tech)

helpdesk/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Count


from helpdesk.decorators import it_staff_required

from tickets.models import Ticket

def chart_data(request):
    data = Ticket.objects.values('type_of_issue').annotate(total=Count('type_of_issue'))

    labels = [item["type_of_issue"] for item in data]
    values = [item["total"] for item in data]
    
    chart_data = {
        'labels': labels,
        'values': values,
        'chart_type': 'pie'
    }
    return JsonResponse(chart_data)

def tech_chart(request):
    data = Ticket.objects.values('assigned_tech__last_name').annotate(total_tickets=Count('assigned_tech'))

    labels = [item["assigned_tech__last_name"] for item in data]
    values = [item["total_tickets"] for item in data]

    tech_chart = {
        'labels': labels,
        'values': values,
        'chart_type': 'doughnut'
    }
    return JsonResponse(tech_chart)

@it_staff_required
def it_dashboard(request):
    tech_id = request.user.id
    if Ticket.objects.exists():
        all_tickets = Ticket.objects.all().order_by('-created_date')
        tickets_by_tech = Ticket.objects.filter(assigned_tech=tech_id).order_by('-created_date')
        context = {
            'tickets': all_tickets,
            'tech_tickets': tickets_by_tech,
        }
    else:
        return render(request, 'helpdesk/it_dashboard.html')
    return render(request, 'helpdesk/it_dashboard.html', context)

helpdesk/templates/helpdesk/it_dashboard.html
{% extends 'base.html' %} 

{% block content %}
<div class="container pt-5">
	<!-- Messages -->
	{% include 'partials/_messages.html' %}

	<h1 class="my-3 pt-4">IT Dashboard</h1>
	<!-- First row-->
	<div class="row">
        <!-- Tickets By Tech Chart -->
      <div class="col">
        <div class="card shadow mb-4">
          <!-- Card Header -->
          <div class="card-header">
            <h4 class="m-0 font-weight-bold text-primary">
              Number of Tickets Per Tech 
            </h4>
          </div>
          <!-- Card Body -->
          <div class="card-body">
            <div class="d-flex justify-content-center">
              <canvas id="techChart"></canvas>
            </div>
          </div>
        </div>
      </div>
    <!-- Begin tickets by type-->
    <div class="col">
      <div class="card shadow mb-4">
        <div class="card-header">
          <h4 class="m-0 font-weight-bold text-primary">
            Tickets By Type
          </h4>
        </div>
        <div class="card-body">
		  	<div class="d-flex justify-content-center">
            	<canvas id="typeTicketChart"></canvas>
			</div>
        </div>
      </div>
    </div>
		<!--end card for tickets by type -->
  </div>
	<!-- First row ends-->
	<!-- Tech Tickets-->
	<div class="accordion mt-5" id="accordionTechTickets">
		<div class="accordion-item">
			<h2 class="accordion-header">
				<button
					class="accordion-button"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#collapseTechTickets"
					aria-expanded="true"
					aria-controls="collapseTechTickets">
					<strong>
						Tickets Assigned to {{ request.user.last_name}}
					</strong>
				</button>
			</h2>
			<div
				id="collapseTechTickets"
				class="accordion-collapse collapse"
				data-bs-parent="#accordionTechTickets">
				<div class="accordion-body">
					<div class="bd-example-snippet bd-code-snippet">
						<div class="bd-example m-0 border-0">
							<div class="table-responsive-md">
							<table class="table table-striped table-hover">
								<thead>
									<tr>
										<th scope="col">Ticket Number</th>
										<th scope="col">Status</th>
										<th scope="col">Created Date</th>
										<th scope="col">Type of Issue</th>
										<th scope="col">Customer</th>
										<th scope="col">Assigned Tech</th>
										<th scope="col">Update</th>
									</tr>
								</thead>
								<tbody>
									{% for ticket in tech_tickets %}
									<tr>
										<th scope="row">{{ ticket.id }}</th>
										<td>{{ ticket.get_status_display }}</td>
										<td>{{ ticket.created_date }}</td>
										<td>
											{{ ticket.get_type_of_issue_display }}
										</td>
										<td>
											{{ ticket.customer.first_name }} 
											{{ ticket.customer.last_name }}
										</td>
										<td>
											{{ ticket.assigned_tech.last_name }}
										</td>
										<td>
											<a
												href="{% url 'update_ticket' ticket.id %}"
												class="btn btn-primary">
												<i
													class="fa-solid fa-pen-to-square"></i>
											</a>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--Tech Tickets end-->
	<!-- All Tickets -->
	<div class="accordion mt-5 mb-5" id="accordionAllTickets">
		<div class="accordion-item">
			<h2 class="accordion-header">
				<button
					class="accordion-button"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#collapseAll"
					aria-expanded="true"
					aria-controls="collapseAll">
					<strong>All Tickets</strong>
				</button>
			</h2>
			<div
				id="collapseAll"
				class="accordion-collapse collapse"
				data-bs-parent="#accordionAllTickets">
				<div class="accordion-body">
					<div class="bd-example-snippet bd-code-snippet">
						<div class="bd-example m-0 border-0">
							<div class="table-responsive-md">
							<table class="table table-striped table-hover">
								<thead>
									<tr>
										<th scope="col">Ticket Number</th>
										<th scope="col">Status</th>
										<th scope="col">Created Date</th>
										<th scope="col">Type of Issue</th>
										<th scope="col">Customer</th>
										<th scope="col">Assigned Tech</th>
									</tr>
								</thead>
								<tbody>
									{% for ticket in tickets %}
									<tr>
										<th scope="row">{{ ticket.id }}</th>
										<td>{{ ticket.get_status_display }}</td>
										<td>{{ ticket.created_date }}</td>
										<td>
											{{ ticket.get_type_of_issue_display}}
										</td>
										<td>
											{{ ticket.customer.first_name }} 
											{{ ticket.customer.last_name }}
										</td>
										<td>
											{{ ticket.assigned_tech.last_name }}
										</td>
										<td>
											<a
												href="{% url 'update_ticket' ticket.id %}"
												class="btn btn-primary">
												<i
													class="fa-solid fa-pen-to-square"></i>
											</a>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- All Tickets end -->
</div>
{% endblock content %}